### ISSUE TITLE
 show Can't resolve 'faker' error! how to solve the problem?

### ISSUE THREAD

**Issue by tytom2003** [reactchartjs/react-chartjs-2#1044]
### Would you like to work on this feature?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

I try using react-chartjs-2 to create a Bar Chart in my reactjs project. I use "yarn add chart.js react-chartjs-2" to install react-chartjs-2  library. and yarn add faker to install faker  library, but it show  Module not found: Error: Can't resolve 'faker'. How to solve the error?

Thank you very much.

### Describe the solution you'd like

i installed faker library, but it cannot fix the error.

**Comment by JBaczuk** [comment]
In the latest version, the author of the [faker](https://www.npmjs.com/package/faker) library removed the functional code, it appears, in order to "make a statement". This is reported as a high severity vulnerability by npm:

```
npm audit report

faker  =6.6.6
Severity: high
Removal of functional code in faker.js - https://github.com/advisories/GHSA-5w9c-rv96-fr7g
fix available via `npm audit fix --force`
Will install faker@5.5.3, which is a breaking change
node_modules/faker

1 high severity vulnerability
```

The docs for 'react-chartjs-2' should probably remove `faker` or at least have a warning that users must install the latest functional version: [5.5.3](https://www.npmjs.com/package/faker/v/5.5.3)
