### ISSUE TITLE
How to give margin between the legend and the actual graph.

### ISSUE THREAD

**Issue by Madhurjya-Gogoi** [reactchartjs/react-chartjs-2#1047]
### Would you like to work on this feature?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

I am not able to give the margin of the legend I want to give some margin between the legend and the actual graph

### Describe the solution you'd like

I am not able to give the margin of the legend I want to give some margin between the legend and the actual graph

**Comment by Arantiryo** [comment]
Hey @Madhurjya-Gogoi 👋 

Creating a margin between the legend and the graph itself can be achieved with a custom plugin like in [this example](https://codesandbox.io/s/fervent-goodall-9lk1pw?file=/App.tsx). You can find more information in a [similar stackoverflow question](https://stackoverflow.com/questions/68788512/react-chart-js-how-do-i-increase-the-space-between-the-legends-and-chart). 

If you'd like to see this as a standard `option` that can be passed to the chart I suggest you file an issue in [Chart.js's repository](https://github.com/chartjs/Chart.js/issues), since this library is just a wrapper over `Chart.js`.

Thank you!

**Comment by Madhurjya-Gogoi** [comment]
Thank you @Arantiryo it's working for me.
