### ISSUE TITLE
[Bug]: Tick Padding applies in all directions around a chart instead of only in one direction.

### ISSUE THREAD

**Issue by MalusGreen** [reactchartjs/react-chartjs-2#1048]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Using the code shown in the sandbox, a tick option padding of size 100 results in padding added to all sides of the chart.

<img width="563" alt="Screen Shot 2022-06-01 at 10 04 38 PM" src="https://user-images.githubusercontent.com/9855990/171534559-5d17fef9-fcbf-41c7-b016-6deadc840c66.png">

Expected behavior is for padding to only be added to the tick, and only to one side of the tick.

### Reproduction

https://nf8rzd.csb.app/

### chart.js version

v3.8.0

### react-chartjs-2 version

v4.1.0

**Comment by Arantiryo** [comment]
Hey @MalusGreen 👋 

This is actually the intended behavior as specified in [Chart.js's docs](https://www.chartjs.org/docs/3.8.0/axes/_common_ticks.html).

If you'd like to see this as an option for setting padding to ticks I suggest you file an issue in [Chart.js's repository](https://github.com/chartjs/Chart.js/issues), since this library is just a wrapper over Chart.js.
