### ISSUE TITLE
How can i show ALL labels on responsive?

### ISSUE THREAD

**Issue by SoyDiego** [reactchartjs/react-chartjs-2#572]
Hi, when i see my website on mobile, the chart  hide labels (2, 4, 6, 8....etc)
How can i show all labels on responsive?

![imagen](https://user-images.githubusercontent.com/19764334/96368046-c8928200-1151-11eb-9ecc-a8e0a0ad93e8.png)

Thanks!

**Comment by owen-duncan-snobel** [comment]
Sorry for a late reply, this seems to be less of a react-chartjs-2 issue but the functionality for chart-js. 

[try this](https://stackoverflow.com/questions/57178499/display-all-labels-in-chart-js) You would just need to try adjusting the options so that the autoskip labels is turned off I believe.
```options: {
  scaleShowValues: true,
  scales: {
    xAxes: [{
      ticks: {
        autoSkip: false
      }
    }]
  }
}
```

**Comment by Arantiryo** [comment]
I’m closing this issue because it has been inactive for a few months.

**Comment by KIRA-14** [comment]
@SoyDiego, Do you have any solution for the above issue? i have the same requirement 
<img width="1792" alt="image" src="https://github.com/reactchartjs/react-chartjs-2/assets/39284822/dd2aeb12-a703-444e-8b76-e4f1766d11cc">
