### ISSUE TITLE
Radar chart tooltip label incorrect

### ISSUE THREAD

**Issue by Holychung** [reactchartjs/react-chartjs-2#581]
I see your [live demo](http://jerairrest.github.io/react-chartjs-2/#/radar), found that radar chart tooltip labels were incorrect.
Like the live demo page, the label should be "Thing 1", "Thing 2", but it appear the data number.
I tried the code in my project it caused the same problem, and I use the origin chart.js is fine.

Thanks!

**Comment by jhonnold** [comment]
Would you mind attaching/referencing some code so I can investigate this further?

**Comment by Holychung** [comment]
I found the live demo site is broken, so I try a simple code about radar chart.

```javascript=
const labels = ['label1', 'label2', 'label3', 'label4', 'label5'];

const radarData = {
  labels: labels,
  datasets: [
    {
      label: 'radar',
      fill: true,
      cubicInterpolationMode: 'monotone',
      backgroundColor: 'rgba(66,129,164,0.2)',
      borderColor: 'rgba(66,129,164,1)',
      pointBorderColor: '#fff',
      pointBackgroundColor: 'rgba(66,129,164,1)',
      data: [1,2,3,4,5]
    }
  ]
};

const radarOptions = {
  maintainAspectRatio: true,
  responsive: true,
  legend: {
    labels: {
      fontColor: 'rgba(248, 184, 82, 1)',
      fontSize: 16
    }
  }
};

class App extends Component {
  render() {
    console.log(radarData)
    return (
      <div className="App container">
        <div className="row">
          <div className="col-6">
            <Radar
              data={radarData}
              width={400}
              height={350}
              options={radarOptions}
            />
          </div>
        </div>
      </div>
    );
  }
}

export default App;
```

And I screenshot the radar graph, I thought the label text must be "label4"?
![](https://i.imgur.com/Vn9ja5S.png)

**Comment by jhonnold** [comment]
The "# of Votes" text that is appearing is [set here](https://github.com/reactchartjs/react-chartjs-2/blob/react16/example/src/charts/Radar.js#L8). This is the intentional behavior of `chart.js`, an example of this can be [seen here](https://www.chartjs.org/samples/latest/charts/area/radar.html).

If it is desired to change what is appearing in the tooltip, that is functionality that can be changed in the [label callback](https://www.chartjs.org/docs/latest/configuration/tooltip.html#label-callback) portion of the options.

**Comment by Holychung** [comment]
okay it works. Thanks a lot!
