### ISSUE TITLE
time x-axis doesn't show first item of labels array

### ISSUE THREAD

**Issue by DenysKanivets** [reactchartjs/react-chartjs-2#587]
I have:
- chart which depends on month
- lines and point shows correctly as in data
- labels array consists of last day of every month
- there is a parser for time in x-axis

but first month is missed
what could be the problem? 

![image](https://user-images.githubusercontent.com/57489658/98291856-72786800-1fb4-11eb-8b37-0208e63dfbf6.png)

part of chartOptions object
```
scales: {
    yAxes: [{
      gridLines: {
        borderDash: [4],
        color: "#f5f5f5"
      },
      ticks: {
        beginAtZero: true,
        // stepSize: 10,
        labelOffset: -10,
        callback (label) {
          if (label >= 1000000) return `$${  label / 1000000  }M`;
          if (label >= 1000) return `$${  label / 1000  }k`;
          if (label <= -1000000) return `-$${  label / -1000000  }M`;
          if (label <= -1000) return `-$${  label / -1000  }k`;
          if (label < 0) return `-$${  -label}`;
          return `$${  label}`;
        }
      },
      // scaleLabel: {
      //   display: true,
      //   labelString: '1k = 1000'
      // }
    }],
    xAxes: [{
      gridLines: {
        borderDash: [4],
        color: "#f5f5f5"
      },
      type: 'time',
      time: {
        parser: 'DD-MM-YYYY',
        tooltipFormat: 'lll',
        unit: 'month',
        unitStepSize: 1,
        displayFormats: {
          'month': 'MMM'
        }
      },
      distribution: 'linear',
      offset: false
    }]
  },
```

thanks for any help!

**Comment by jhonnold** [comment]
I was able to recreate this issue [here](https://codesandbox.io/s/vigorous-monad-5k565), so it seems to be related to the `Chart.js` library directly and not this one directly.

As far as I can tell, the y-axis is slightly shifted on your screenshot indicating that the 31st is being rendered, however, because it is not the first of the month, the label is not being rendered. This seems to be the case even when the date is the 2nd of the month.

The only suggestion I have is to rely on your own method for generating the labels rather than the time parser.

**Comment by Arantiryo** [comment]
I’m closing this issue because it has been answered and has been inactive for a while.
