### ISSUE TITLE
Are there plans to make react-chartjs-2 truly tree-shakeable?

### ISSUE THREAD

**Issue by alimirakim** [reactchartjs/react-chartjs-2#706]
I noticed using source-map-explorer that all of chart.js 3.x is being imported, so the tree-shakeable benefits from chart.js 3.x are lost by using this library. When you only need 1-2 chart components from the bunch, that's kind of a big hit, so I'm considering if our project may be better to just switching to chart.js directly. If react-chartjs-2 will gain the eventual benefits of 3.x's tree-shaking though, it would save me some work :) . Any plans for it at all?

**Comment by pabrodez** [comment]
Maybe the reason is that it's using `import Chart from 'chart.js/auto';` , which registers all controllers, elements, scales and plugins. 
And it makes sense because the library won't know what elements the user will need beforehand. 
Do you guys think it'd be possible to not register any element in library (so remove `import Chart from 'chart.js/auto';` ) and only import the `Chart` class (`import { Chart } from 'chart.js';)? Then, the user would need to import and register those elements that they'd need for the given type of chart in their project.

**Comment by dangreen** [comment]
@alimirakim @pabrodez Released in [v4.0.0](https://github.com/reactchartjs/react-chartjs-2/releases/tag/v4.0.0). [Migration guide](https://react-chartjs-2.netlify.app/docs/migration-to-v4).

**Comment by alimirakim** [comment]
@dangreen Thanks so much for the update and heads up. Appreciate the link to the migration guide!
