### ISSUE TITLE
[Bug]: Legend custom onClick error

### ISSUE THREAD

**Issue by cristi-iacob** [reactchartjs/react-chartjs-2#955]
### 🦄

- [ ] Would you like to work on a fix?

### Current and expected behavior

Hi!

I am trying to implement my own custom onClick handler for the legend plugin for a Pie chart. The problem is that if I'm trying to use a method which updates the internal chart variables, I receive the following error with the corresponding stack trace: 
![image](https://user-images.githubusercontent.com/52404495/147222575-19d657e4-e454-4bd4-88c0-d24413830a50.png)

The custom implementation is in fact the default implementation from the [documentation](https://www.chartjs.org/docs/latest/configuration/legend.html#custom-on-click-actions). 

The onClick method overwrite works (i.e. if I console.log() something in the custom method, it works). The problem is the update of the chart. I would like to keep the default behavior (with the nice animation) but also add some custom functionality to the onClick method.

I reproduced the behavior in a Sandbox. You can find it [here](https://codesandbox.io/s/exciting-dhawan-gluc8?file=/src/App.js). If you remove the custom onClick method, the component works as expected. I also have some custom tooltip callbacks functionalities, which work properly. I have also tried with multiple versions of chart.js and react-chartjs-2, but this problem exists in all of them. 

Thank you! 

### Reproduction

https://codesandbox.io/s/exciting-dhawan-gluc8?file=/src/App.js

### chart.js version

v.3.6.2

### react-chartjs-2 version

v3.0.4

**Comment by dangreen** [comment]
@cristi-iacob Hi. [It looks like an issue with chart.js itself](https://codesandbox.io/s/ecstatic-waterfall-wihps?file=/src/index.js), not an issue with react wrapper. So please [open the issue in chart.js repo](https://github.com/chartjs/Chart.js/issues).

**Comment by LeeLenaleee** [comment]
This is not an issue in chart.js, it is an issue in your custom code.

You are trying to use the default `onClick` while using a pie chart. Pie charts override the `generateLabels` and `onClick` function.
Because they override the `generateLabels` function and dont need the `datasetIndex` field (because of how the legend for this chart type works) it isnt included. So if you want to use this legend onClick you will also need to either add the `datasetIndex` field to the meta data or use the default overriden onClick.

Pie chart onClick function:
https://github.com/chartjs/Chart.js/blob/master/src/controllers/controller.doughnut.js#L392-L395

Pie chart with default `onClick` and `generateLegend` function:
https://jsfiddle.net/Leelenaleee/7qa4khj8/7/
